/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class colorserver_ColorServer */

#ifndef _Included_colorserver_ColorServer
#define _Included_colorserver_ColorServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     colorserver_ColorServer
 * Method:    requestColors
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_colorserver_ColorServer_requestColors
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     colorserver_ColorServer
 * Method:    updateRevision
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_colorserver_ColorServer_updateRevision
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
